---
title: Anima
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: warfan2007@gmail.com
description: 'An OS for the modern internet user.

'
baseurl: "/Anima-OS.com/"
url: https://anima-os.com
logo: "/Anima-OS.com/images/logo.svg"
exclude:
- ".travis"
- vendor
social:
  links:
  - https://github.com/anima-os
  - https://plus.google.com/u/0/100355783508323292342
  - https://plus.google.com/u/0/communities/115722443491803015565
  - https://www.facebook.com/Liri-935614733238741
  - https://twitter.com/liridev
google_site_verification: true
repository: anima-os/anima-os.com
github:
  repo: https://github.com/anima-os/anima-os.com
social_networks:
  github: anima-os
  gitter: anima-os/lobby
  facebook: Anima-1777750955872032
  youtube: PLtwK8RgezTNqKYny0vEAY0pEOrYU29-GP
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-toc
